### ISSUE TITLE
Dependencies and devDependencies out of date

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-sdk-mock#161]
https://david-dm.org/dwyl/aws-sdk-mock
![image](https://user-images.githubusercontent.com/194400/49454737-b0bfe800-f7dd-11e8-8a16-ed57eed81c5f.png)

https://david-dm.org/dwyl/aws-sdk-mock?type=dev
![image](https://user-images.githubusercontent.com/194400/49454828-e5cc3a80-f7dd-11e8-9bf4-1e0dbd516d08.png)

# Todo
+ [ ] Update dependency on `sinon` and `aws-sdk`
+ [ ] Update devDependency on `nyc`
+ [ ] Bonus: Add `snyk` security checking + badge see: https://github.com/dwyl/repo-badges/issues/32#issuecomment-442962992

**Comment by nelsonic** [comment]
Remove "_broken_" download stats indicator:
![image](https://user-images.githubusercontent.com/194400/49460050-5d9f6280-f7e8-11e8-98ba-849d6b968b91.png)
