### ISSUE TITLE
Chore: Update Badges in `README.md`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-sdk-mock#288]
Sadly the badges situation in the `README.md` 
and correspondingly on `NPM` https://www.npmjs.com/package/aws-sdk-mock
are stale:

<img width="1228" alt="image" src="https://github.com/dwyl/aws-sdk-mock/assets/194400/f6942131-5511-4a4f-99f2-d7608a7946e9">

# Todo

+ [ ] Update `GitHub` CI build badge: ![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/aws-sdk-mock/ci.yml?label=build&style=flat-square&branch=main)
```md
![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/aws-sdk-mock/ci.yml?label=build&style=flat-square&branch=main)
```

+ [ ] Add hits badge: [![HitCount](https://hits.dwyl.com/dwyl/aws-sdk-mock.svg?style=flat-square)](http://hits.dwyl.com/dwyl/aws-sdk-mock)
```md
[![HitCount](https://hits.dwyl.com/dwyl/aws-sdk-mock.svg?style=flat-square)](http://hits.dwyl.com/dwyl/aws-sdk-mock)
```

+ [ ] Update dependency badge:  ![Libraries.io dependency status for latest release](https://img.shields.io/librariesio/release/npm/aws-sdk-mock?style=flat-square)
```md
![Libraries.io dependency status for latest release](https://img.shields.io/librariesio/release/npm/aws-sdk-mock?style=flat-square)
```
+ [ ] NPM Package version: [![npm package version](https://img.shields.io/npm/v/aws-sdk-mock.svg?style=flat-square)](https://www.npmjs.com/package/aws-sdk-mock)
```md
[![npm package version](https://img.shields.io/npm/v/aws-sdk-mock.svg?style=flat-square)](https://www.npmjs.com/package/aws-sdk-mock)
```

Borrow from: https://github.com/dwyl/hapi-auth-jwt2/edit/main/README.md
```md
[![Known Vulnerabilities](https://snyk.io/test/github/dwyl/hapi-auth-jwt2/badge.svg?targetFile=package.json&style=flat-square)](https://snyk.io/test/github/dwyl/hapi-auth-jwt2?targetFile=package.json)
![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/hapi-auth-jwt2/ci.yml?label=build&style=flat-square&branch=main)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/hapi-auth-jwt2/main.svg?style=flat-square)](http://codecov.io/github/dwyl/hapi-auth-jwt2?branch=main)
[![Inline docs](http://inch-ci.org/github/dwyl/hapi-auth-jwt2.svg?branch=main&style=flat-square)](http://inch-ci.org/github/dwyl/hapi-auth-jwt2)
[![HAPI 21.1.0](http://img.shields.io/badge/hapi-21.1.0-brightgreen.svg?style=flat-square "Latest Hapi.js")](http://hapijs.com)
[![Node.js Version](https://img.shields.io/node/v/hapi-auth-jwt2.svg?style=flat-square "Node.js 14.x, 16.x & 18.x supported")](http://nodejs.org/download/)
[![contributions welcome](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat-square)](https://github.com/dwyl/hapi-auth-jwt2/issues)
[![HitCount](http://hits.dwyl.com/dwyl/hapi-auth-jwt2.svg)](http://hits.dwyl.com/dwyl/hapi-auth-jwt2)
[![npm package version](https://img.shields.io/npm/v/hapi-auth-jwt2.svg?style=flat-square)](https://www.npmjs.com/package/hapi-auth-jwt2)
```

**Comment by nelsonic** [comment]
This is comparatively "low" priority for me compared to my other tasks ...
But just going to get it done fast so that the repo looks better.
(Just found out that ***`NASA`*** are using the package ... so tidying up to avoid bad impression)

**Comment by nelsonic** [comment]
Badges:

[![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/aws-sdk-mock/ci.yml?label=build&style=flat-square&branch=main)](https://github.com/dwyl/aws-sdk-mock/actions/workflows/ci.yml)
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/aws-sdk-mock/master.svg?style=flat-square)](http://codecov.io/github/dwyl/aws-sdk-mock?branch=master)
[![Known Vulnerabilities](https://snyk.io/test/github/dwyl/aws-sdk-mock/badge.svg?targetFile=package.json&style=flat-square)](https://snyk.io/test/github/dwyl/aws-sdk-mock?targetFile=package.json)
[![Node.js Version](https://img.shields.io/node/v/aws-sdk-mock.svg?style=flat-square "Node.js 14.x, 16.x & 18.x supported")](http://nodejs.org/download/)
![npm monthly downloads](https://img.shields.io/npm/dm/aws-sdk-mock?style=flat-square)
[![npm package version](https://img.shields.io/npm/v/aws-sdk-mock.svg?style=flat-square&color=bright-green)](https://www.npmjs.com/package/aws-sdk-mock)
[![HitCount](https://hits.dwyl.com/dwyl/aws-sdk-mock.svg?style=flat-square)](http://hits.dwyl.com/dwyl/aws-sdk-mock)
[![contributions welcome](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat-square)](https://github.com/dwyl/aws-sdk-mock/issues)

**Comment by nelsonic** [comment]
PR: #289
